excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://JamboreeIndia.github.io
title: Jamboree India
tagline: "Transforming Careers, Transforming Lives"
description: Jamboree, the most trusted Institute for Preparation (GMAT, GRE, SAT, IELTS, and TOEFL) to admissions counseling since 1995.
paginate: 5